Error handling for cache
actions/setup-go pull request #238
Opened 2022-06-14 09:11 UTC by vsafonkin

Added logic to handle cache errors similarly [`actions/cache`](https://github.com/actions/cache):
https://github.com/actions/cache/blob/main/src/restore.ts#L33

Execution of the action is not interrupted if the cache restore operation returns an error.

2022-06-14 09:27 UTC, marko-zivic-93 approved these changes

2022-06-14 17:55 UTC, brcrista requested changes
This should probably go in the [`restoreCache()` function from the `@actions/cache` toolkit package](https://github.com/actions/toolkit/blob/b5f31bb5a25d129441c294fc81ba7f92f3e978ba/packages/cache/src/cache.ts#L65).  That way everything that uses caching will handle 503s correctly.

2022-06-28 12:23 UTC, marko-zivic-93 approved these changes

2022-06-28 13:16 UTC, marko-zivic-93 approved these changes

2022-06-29 07:18 UTC, panticmilos approved these changes

2022-06-29 15:04 UTC, brcrista commented
Upstream fix: https://github.com/actions/toolkit/pull/1122

2022-06-30 12:11 UTC, vsafonkin commented
@brcrista, please review

2022-06-30 13:22 UTC, dmitry-shibanov approved these changes

2022-06-30 13:41 UTC, brcrista requested changes
We just have to bump `@actions/cache` to v3: https://github.com/actions/toolkit/pull/1122

2022-06-30 13:41 UTC, brcrista commented on src/cache-save.ts
> +  if (cacheId == -1) {
```suggestion
  if (cacheId === -1) {
```

2022-06-30 13:41 UTC, brcrista approved these changes

2022-07-01 07:44 UTC, marko-zivic-93 approved these changes

2022-07-01 07:45 UTC, merged