Pass the token input through on GHES
actions/setup-go pull request #277
Opened 2022-10-17 10:53 UTC by dmitry-shibanov

**Description:**
In scope of this pull request we make available to pass GitHub token on GHES.

**Related issue:**
https://github.com/actions/runner-images-internal/issues/4479

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

2022-10-17 11:20 UTC, marko-zivic-93 approved these changes

2022-10-17 12:55 UTC, e-korolevskii approved these changes

2022-10-17 13:08 UTC, IvanZosimov approved these changes

2022-10-17 13:40 UTC, vsafonkin approved these changes

2022-10-21 20:35 UTC, brcrista requested changes
This also needs to the change to `action.yml` here: https://github.com/actions/setup-python/pull/443/files

On GHES, this will start using `GITHUB_TOKEN` ([the default value for the `token` input](https://github.com/actions/setup-go/blob/c4a742cab115ed795e34d4513e2cf7d472deb55f/action.yml#L14)) to make calls to github.com.  But, the GHES token isn't valid on github.com.

2022-10-24 07:20 UTC, marko-zivic-93 approved these changes

2022-10-25 10:37 UTC, MaksimZhukov approved these changes

2022-10-25 18:38 UTC, brcrista approved these changes

2022-11-02 11:21 UTC, merged