Add stable and oldstable aliases
actions/setup-go pull request #292
Opened 2022-11-20 17:16 UTC by panticmilos

**Description:**
In the scope of this PR, we are adding support for more natural aliases in the Go eco-system, `stable` and `oldstable`. 

**Related issue:**
#232

**Check list:**
- [x] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

2022-11-21 12:41 UTC, dmitry-shibanov commented on src/installer.ts
> +export type StableAliasType = 'stable' | 'oldstable';
I think it is better to create enums or use a similar approach as for [setup-dotnet](https://github.com/actions/setup-dotnet/blob/main/src/setup-dotnet.ts#L8-L16).

2022-11-21 12:41 UTC, dmitry-shibanov commented on src/main.ts
> +      if (versionSpec === 'stable' || versionSpec === 'oldstable') {
I think it is better to create enums or use a similar approach as for [setup-dotnet](https://github.com/actions/setup-dotnet/blob/main/src/setup-dotnet.ts#L8-L16).

2022-11-21 12:42 UTC, dmitry-shibanov commented
Could you please update documentation with new syntax description.

2022-11-21 16:21 UTC, dmitry-shibanov commented on src/main.ts
> +    return releases[0].version;
we need to add check for architecture.

2022-11-21 16:21 UTC, dmitry-shibanov commented on src/main.ts
> +    core.info(`Oldstable version resolved as ${uniqueVersions[1]}`);
I think it is better to put core.info after `oldstableVersion` to show the full version.

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/main.ts
> +async function resolveStableVersionInput(
Could you please move this logic to the `installer.ts`

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/main.ts
> +      }
Could you please move this logic to the `installer.ts`

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/installer.ts
> +  let rel = await tc.findFromManifest(versionSpec, stable, releases, arch);
I think we can keep it const

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/installer.ts
> +  releases = releases ? releases : await getAllManifestReleases(auth);
Could you please change it to this snippet:
```
  if (!manifest) {
    core.debug('No manifest cached');
    manifest = await getManifest(auth);
  }
```

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/installer.ts
> +export async function getAllToolCacheReleases(arch = os.arch()) {
Could you please rename it to `getAllToolCacheVersions`

2022-11-23 13:51 UTC, dmitry-shibanov commented on src/installer.ts
> +export async function getAllManifestReleases(auth: string | undefined) {
Could you please rename it to `getManifest`

2022-11-23 14:15 UTC, marko-zivic-93 approved these changes

2022-11-23 14:15 UTC, marko-zivic-93 commented on src/main.ts
> +    let versionSpec = resolveVersionInput();
When you move the logic down that Dmitry suggested to installer.ts, you will no longer need this variable to be defined as let, you will be able to use const again.

2022-11-23 15:16 UTC, brcrista commented on README.md
> +- stable and olstable aliases
```suggestion
- stable and oldstable aliases
```

2022-11-23 15:17 UTC, brcrista commented on .github/workflows/versions.yml
> +      - name: Setup Go and check latest
`check-latest` isn't set for this step and the step in `oldstable-no-check-latest`

2022-11-23 15:23 UTC, brcrista commented on README.md
> +Given the fact that Go doesn't use semver syntax ranges, and that many Go projects want to run tests based on `stable` and `oldstable` aliases, these aliases are introduced in the action as possible
Can we have `stable` and `oldstable` imply `check-latest`?

2022-11-23 15:25 UTC, brcrista requested changes
Can we have `stable` and `oldstable` imply `check-latest`?

That will simplify the user-facing behavior, and I suspect it aligns with what people want when they ask for `stable`.  It will also reduce the number of cases we have to cover in our tests.

2022-11-23 18:16 UTC, brcrista approved these changes

2022-11-24 13:39 UTC, e-korolevskii approved these changes

2022-11-24 15:58 UTC, dmitry-shibanov commented on src/main.ts
> +
Could you please change it to `const version = path.basename(path.dirname(installDir))`

2022-11-24 15:58 UTC, dmitry-shibanov commented on src/utils.ts
> +export const IS_WINDOWS = process.platform === 'win32';
I think we can remove it.

2022-11-24 15:58 UTC, dmitry-shibanov commented on src/main.ts
> +    let versionSpec = resolveVersionInput();
Could you please revert changes and keep it const.

2022-11-24 15:58 UTC, dmitry-shibanov commented on src/installer.ts
> +export async function resolveVersionFromManifest(
I think we can remove export.

2022-11-24 15:58 UTC, dmitry-shibanov commented on .github/workflows/versions.yml
> +          architecture: x64
I think we can remove architecture.

2022-12-06 14:18 UTC, closed without merging