adding support for linux-ppc64le
actions/setup-go pull request #329
Opened 2023-02-06 14:48 UTC by adilhusain-s

*Made changes to support linux-ppc64le  arch 

please review and merge.

2023-08-03 13:22 UTC, dsame commented
Hello @adilhusain-s , can you please add e2e test to make sure the action produces inux-ppc64le binaries and change the README to reflect new input values.

2023-08-11 10:08 UTC, dsame approved these changes

2023-08-14 09:17 UTC, dmitry-shibanov approved these changes

2023-08-16 06:05 UTC, marko-zivic-93 approved these changes

2023-08-16 06:13 UTC, dsame requested changes
Since 1.21.x both  ppc64 and ppc64le are supported  https://go.dev/dl/?mode=json&include=all and the PR can not be accepted in the current state.

It must be modified either to accept `ppc64` and `ppc64le` arch or use `ppc64` for ppc64le archtecture only for the go version below 1.21

2023-08-16 14:05 UTC, dsame commented
Hello @adilhusain-s finally we went to conclusion there's no need in the PR since 1.21 supports both ppc64 and ppc64le and architectures can be used without the translation.

2023-08-16 14:05 UTC, closed without merging